In [2]:
import numpy as np
import pandas as pd

In [3]:
team_data = pd.read_csv("four_factors.csv",index_col=[0])
game_data = pd.read_csv('2022_Season.csv', index_col =[0])
print(team_data.head(),game_data.head())

   Unnamed: 0.1  Unnamed: 0.1.1  Unnamed: 0.1.1.1       Team Conference  \
0             0               0                 0    Gonzaga        WCC
1             1               1                 1     Baylor        B12
2             2               2                 2       Iowa        B10
3             3               4                 4        LSU        SEC
4             4               5                 5  Villanova         BE

   AdjTempo  AdjTempo.Rank  AdjOE  AdjOE.Rank  Off-eFG%  ...  AdjDE.Rank  \
0      73.8              7  126.4           1      61.0  ...          11
1      67.4            213  125.0           2      56.5  ...          22
2      69.9             93  123.5           3      54.7  ...          75
3      70.6             70  120.1           5      52.3  ...         124
4      64.2            336  119.0           6      53.2  ...          66

   Def-eFG%  Def-eFG%.Rank  Def-TO%  Def-TO%.Rank  Def-OR%  Def-OR%.Rank  \
0      47.7             61     19.3           137     23.8            31
1      48.9            121     24.4             4     30.6           274
2      48.8            115     16.1           314     29.1           220
3      48.5             99     17.9           231     32.1           312
4      51.0            216     18.4           198     25.7            84

   Def-FTRate  Def-FTRate.Rank  NCAA
0        25.7               43   334
1        31.3              167   108
2        22.2                6    91
3        29.8              135   269
4        25.6               40    58

[5 rows x 28 columns]       GameID  Season             DateTime AwayTeam HomeTeam  AwayTeamID  \
3739   41159    2022  2022-01-29T16:16:00    SOUTH    ALCST         305
3740   40454    2022  2022-01-29T16:16:00     TAMU     NWST         292
3741   42056    2022  2022-01-29T16:17:00    HOWRD      NCC         195
3742   42055    2022  2022-01-29T16:19:00   NORFST   SCARST         191
3743   40447    2022  2022-01-29T16:25:00   NCASHE    PRESB          80

      HomeTeamID  AwayTeamScore  HomeTeamScore  GlobalAwayTeamID  \
3739         307           98.0          104.0          60000305
3740         301          116.0          138.0          60000292
3741         197          115.0          113.0          60000195
3742         190          133.0          106.0          60000191
3743          89          104.0          103.0          60000080

      GlobalHomeTeamID
3739          60000307
3740          60000301
3741          60000197
3742          60000190
3743          60000089

In [4]:
team_data.columns.str.match("Unnamed")
team_data = team_data.loc[:,~team_data.columns.str.match("Unnamed")]

In [5]:
team_data = team_data.drop(['Off-OR%.Rank','Off-TO%.Rank','Off-eFG%.Rank','AdjTempo.Rank','AdjOE.Rank','Def-OR%.Rank','Def-TO%.Rank','Def-FTRate.Rank','Def-eFG%.Rank','AdjDE.Rank'],axis=1)
print(team_data.head())

        Team Conference  AdjTempo  AdjOE  Off-eFG%  Off-TO%  Off-OR%  \
0    Gonzaga        WCC      73.8  126.4      61.0     16.1     30.1
1     Baylor        B12      67.4  125.0      56.5     16.5     37.3
2       Iowa        B10      69.9  123.5      54.7     13.3     30.8
3        LSU        SEC      70.6  120.1      52.3     15.6     31.4
4  Villanova         BE      64.2  119.0      53.2     13.7     27.8

   Off-FTRate  Off-FTRate.Rank  AdjDE  Def-eFG%  Def-TO%  Def-OR%  Def-FTRate  \
0        35.7               66   89.9      47.7     19.3     23.8        25.7
1        26.5              295   91.1      48.9     24.4     30.6        31.3
2        32.0              158   96.7      48.8     16.1     29.1        22.2
3        34.0              106   99.8      48.5     17.9     32.1        29.8
4        30.0              210   96.0      51.0     18.4     25.7        25.6

   NCAA
0   334
1   108
2    91
3   269
4    58

In [6]:
feb_game = game_data.iloc[598:1599]
print(feb_game.head())

      GameID  Season             DateTime AwayTeam HomeTeam  AwayTeamID  \
4337   37945    2022  2022-02-10T19:00:00     GAST    COAST         328
4338   37498    2022  2022-02-10T19:00:00    NEAST      DEL         131
4339   37496    2022  2022-02-10T19:00:00    HOFST   DREXEL         128
4340   42784    2022  2022-02-10T19:00:00    INDST    EVANS         207
4341   40556    2022  2022-02-10T19:00:00    STFPA   FAIRDK         225

      HomeTeamID  AwayTeamScore  HomeTeamScore  GlobalAwayTeamID  \
4337          81           93.0           77.0          60000328
4338         133           93.0          113.0          60000131
4339         132          127.0          112.0          60000128
4340         203          123.0          118.0          60000207
4341         224          119.0          100.0          60000225

      GlobalHomeTeamID
4337          60000081
4338          60000133
4339          60000132
4340          60000203
4341          60000224

In [7]:
home_team_fg = []
home_team_or = []
home_team_ft = []
home_team_to = []

away_team_fg = []
away_team_or = []
away_team_ft = []
away_team_to = []

point_spread = []
for index,game in feb_game.iterrows():
    away_ID = game['AwayTeamID']
    home_ID = game['HomeTeamID']
    home_team = team_data.loc[team_data['NCAA'] == home_ID]
    away_team = team_data.loc[team_data['NCAA'] == away_ID]
    if home_team.empty or away_team.empty:
        continue 
    home_team_fg.append(float(home_team['Off-eFG%']  -  home_team['Def-eFG%']))
    home_team_or.append(float(home_team['Off-OR%']  -  home_team['Def-OR%']))
    home_team_ft.append(float(home_team['Off-FTRate']  -  home_team['Def-FTRate']))
    home_team_to.append(float(home_team['Off-TO%']  -  home_team['Def-TO%']))
    away_team_fg.append(float(away_team['Off-eFG%']  -  away_team['Def-eFG%']))
    away_team_or.append(float(away_team['Off-OR%']  -  away_team['Def-OR%']))
    away_team_ft.append(float(away_team['Off-FTRate']  -  away_team['Def-FTRate']))
    away_team_to.append(float(away_team['Off-TO%']  -  away_team['Def-TO%']))
    point_spread.append(float(game['HomeTeamScore'] -  game['AwayTeamScore']))
data = {
    'home_team_fg':home_team_fg,
    'home_team_or':home_team_or,
    'home_team_ft':home_team_ft,
    'home_team_to':home_team_to,
    'away_team_fg':away_team_fg,
    'away_team_or':away_team_or,
    'away_team_ft':away_team_ft,
    'away_team_to':away_team_to,
    'point_spread':point_spread
}
cleaned_data = pd.DataFrame(data)
display(cleaned_data)

,home_team_fg,home_team_or,home_team_ft,home_team_to,away_team_fg,away_team_or,away_team_ft,away_team_to,point_spread
0,1.4,2.3,6.4,4.0,3.3,-6.1,-3.2,2.3,20.0
1,3.2,4.6,0.9,3.5,-0.3,0.3,7.4,0.0,-15.0
2,5.7,-4.6,-0.2,6.6,-3.7,0.1,-4.6,0.2,23.0
3,0.9,-0.2,7.5,-4.2,-1.3,1.9,-16.4,-0.4,-6.0
4,-1.9,0.4,-1.9,-0.6,-4.7,-5.6,-5.4,2.1,20.0
...,...,...,...,...,...,...,...,...,...
544,-10.0,-11.2,-0.2,1.6,-0.9,-1.3,0.8,-3.5,18.0
545,-0.3,0.3,7.4,0.0,-0.4,-1.8,-6.4,-1.4,7.0
546,-0.8,14.5,7.3,1.3,3.2,-4.8,4.2,-3.9,14.0
547,5.9,1.7,9.8,-2.8,0.1,-6.0,-6.9,-0.7,33.0
548,6.9,3.6,-2.0,2.9,7.6,6.7,-4.8,-7.9,-11.0

In [8]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [9]:
print(cleaned_data['point_spread'])

0      20.0
1     -15.0
2      23.0
3      -6.0
4      20.0
       ...
544    18.0
545     7.0
546    14.0
547    33.0
548   -11.0
Name: point_spread, Length: 549, dtype: float64

In [10]:
# prd_data = cleaned_data.drop('point_spread',axis=1)
# prd = np.array(prd_data['home_team_fg','home_team_or','home_team_ft','home_team_to','away_team_fg','away_team_or','away_team_ft','away_team_to']).reshape(-1,1)
# act = np.array(cleaned_data['point_spread']).reshape(-1, 1)
train_data_dm,test_data_dm = train_test_split(cleaned_data,train_size = 0.8,random_state=3)
independent_var = ['home_team_fg','home_team_or','home_team_ft','home_team_to','away_team_fg','away_team_or','away_team_ft','away_team_to']
regr = LinearRegression()
regr.fit(train_data_dm[independent_var],train_data_dm['point_spread'])
print(regr.score(test_data_dm[independent_var],test_data_dm['point_spread']))

0.13313409333233672

In [14]:
game = {
    'home_team_fg':[2.98],
    'home_team_or':[3.45],
    'home_team_ft':[3.81],
    'home_team_to':[-1],
    'away_team_fg':[11.2],
    'away_team_or':[3.61],
    'away_team_ft':[2.89],
    'away_team_to':[0.64]
}
game_pred_x = pd.DataFrame.from_dict(game)
# x = np.array(game_pred_x[independent_var])
regr.predict(game_pred_x[independent_var])

array([-0.97714139])